# Generated by Django 2.0.2 on 2018-03-18 10:35

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceWaterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_o_d', models.FloatField()),
                ('b_c_d', models.FloatField()),
                ('t_c_o', models.FloatField()),
                ('t_d_s', models.FloatField()),
                ('chlorides', models.FloatField()),
                ('colour', models.FloatField()),
                ('s_a_r', models.FloatField()),
                ('boron', models.FloatField()),
                ('sulphates', models.FloatField()),
                ('nitrates', models.FloatField()),
                ('free_ammonia', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('ph_val', models.FloatField(validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)])),
                ('arsenic', models.FloatField()),
                ('iron', models.FloatField()),
                ('fluoride', models.FloatField()),
                ('lead', models.FloatField()),
                ('water_body_name', models.CharField(max_length=140)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('quality_index', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
