# Generated by Django 2.0.2 on 2018-03-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='arsenic',
            new_name='biological_oxygen_demand',
        ),
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='b_c_d',
            new_name='calcium',
        ),
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='boron',
            new_name='dissolved_oxygen',
        ),
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='colour',
            new_name='electrical_conductivity',
        ),
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='conductivity',
            new_name='magnesium',
        ),
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='d_o_d',
            new_name='nitrate',
        ),
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='fluoride',
            new_name='sulphate',
        ),
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='free_ammonia',
            new_name='total_alkalinity',
        ),
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='iron',
            new_name='total_dissolved_solids',
        ),
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='lead',
            new_name='total_hardness',
        ),
        migrations.RenameField(
            model_name='surfacewaterdata',
            old_name='nitrates',
            new_name='total_suspended_solids',
        ),
        migrations.RemoveField(
            model_name='surfacewaterdata',
            name='s_a_r',
        ),
        migrations.RemoveField(
            model_name='surfacewaterdata',
            name='sulphates',
        ),
        migrations.RemoveField(
            model_name='surfacewaterdata',
            name='t_c_o',
        ),
        migrations.RemoveField(
            model_name='surfacewaterdata',
            name='t_d_s',
        ),
    ]
