# Generated by Django 2.0.2 on 2018-03-28 10:03

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('input', '0002_auto_20180319_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceWaterDataTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissolved_oxygen', models.FloatField()),
                ('ph_val', models.FloatField(validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)])),
                ('electrical_conductivity', models.FloatField()),
                ('total_dissolved_solids', models.FloatField()),
                ('total_alkalinity', models.FloatField()),
                ('total_hardness', models.FloatField()),
                ('total_suspended_solids', models.FloatField()),
                ('calcium', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('chlorides', models.FloatField()),
                ('nitrate', models.FloatField()),
                ('sulphate', models.FloatField()),
                ('biological_oxygen_demand', models.FloatField()),
                ('quality_index', models.FloatField()),
                ('water_body_name', models.CharField(max_length=140)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
