# Generated by Django 2.0.2 on 2018-03-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_approve_rejet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rejet',
            new_name='Reject',
        ),
    ]
