# Generated by Django 2.0.2 on 2018-03-30 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_auto_20180330_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissolved_oxygen', models.FloatField()),
                ('ph_val', models.FloatField(validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)])),
                ('electrical_conductivity', models.FloatField(null=True)),
                ('total_dissolved_solids', models.FloatField(null=True)),
                ('total_alkalinity', models.FloatField(null=True)),
                ('total_hardness', models.FloatField(null=True)),
                ('total_suspended_solids', models.FloatField(null=True)),
                ('calcium', models.FloatField(null=True)),
                ('magnesium', models.FloatField(null=True)),
                ('chlorides', models.FloatField(null=True)),
                ('sulphate', models.FloatField(null=True)),
                ('biological_oxygen_demand', models.FloatField(null=True)),
                ('quality_index', models.FloatField(null=True)),
                ('temperature', models.FloatField()),
                ('colour', models.CharField(max_length=25)),
                ('odour', models.IntegerField()),
                ('chemical_oxygen_demand', models.FloatField()),
                ('iron', models.FloatField()),
                ('potassium', models.FloatField()),
                ('phosphate', models.FloatField()),
                ('nitrate', models.FloatField()),
                ('nitrite', models.FloatField()),
                ('boron', models.FloatField()),
                ('bicarbonate', models.FloatField()),
                ('fluoride', models.FloatField()),
                ('total_plate_count', models.FloatField()),
                ('total_coliform', models.FloatField()),
                ('fecal_coliform', models.FloatField()),
                ('e_coliform', models.FloatField()),
                ('sodium', models.FloatField()),
                ('carbonate', models.FloatField()),
                ('silicate', models.FloatField()),
                ('total_organic_carbon', models.FloatField()),
                ('total_kjelhdal_nitrogen', models.FloatField()),
                ('ammonia_nitrogen', models.FloatField()),
                ('cyanide', models.FloatField()),
                ('arsenic', models.FloatField()),
                ('cadium', models.FloatField()),
                ('mercury', models.FloatField()),
                ('chromium', models.FloatField()),
                ('lead', models.FloatField()),
                ('zinc', models.FloatField()),
            ],
        ),
    ]
