# Generated by Django 2.0.2 on 2018-03-30 09:54

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('input', '0006_waterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterDataTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissolved_oxygen', models.FloatField()),
                ('ph_val', models.FloatField(validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)])),
                ('electrical_conductivity', models.FloatField(null=True)),
                ('total_dissolved_solids', models.FloatField(null=True)),
                ('total_alkalinity', models.FloatField(null=True)),
                ('total_hardness', models.FloatField(null=True)),
                ('total_suspended_solids', models.FloatField(null=True)),
                ('calcium', models.FloatField(null=True)),
                ('magnesium', models.FloatField(null=True)),
                ('chlorides', models.FloatField(null=True)),
                ('sulphate', models.FloatField(null=True)),
                ('biological_oxygen_demand', models.FloatField(null=True)),
                ('quality_index', models.FloatField(null=True)),
                ('temperature', models.FloatField()),
                ('colour', models.CharField(max_length=25)),
                ('odour', models.IntegerField()),
                ('chemical_oxygen_demand', models.FloatField()),
                ('iron', models.FloatField()),
                ('potassium', models.FloatField()),
                ('phosphate', models.FloatField()),
                ('nitrate', models.FloatField()),
                ('nitrite', models.FloatField()),
                ('boron', models.FloatField()),
                ('bicarbonate', models.FloatField()),
                ('fluoride', models.FloatField()),
                ('total_plate_count', models.FloatField()),
                ('total_coliform', models.FloatField()),
                ('fecal_coliform', models.FloatField()),
                ('e_coliform', models.FloatField()),
                ('sodium', models.FloatField()),
                ('carbonate', models.FloatField()),
                ('silicate', models.FloatField()),
                ('total_organic_carbon', models.FloatField()),
                ('total_kjelhdal_nitrogen', models.FloatField()),
                ('ammonia_nitrogen', models.FloatField()),
                ('cyanide', models.FloatField()),
                ('arsenic', models.FloatField()),
                ('cadium', models.FloatField()),
                ('mercury', models.FloatField()),
                ('chromium', models.FloatField()),
                ('lead', models.FloatField()),
                ('zinc', models.FloatField()),
                ('water_body_name', models.CharField(default='Ganga', max_length=140)),
                ('lat', models.FloatField(default=78.123445)),
                ('lon', models.FloatField(default=78.123445)),
                ('laboratory', models.CharField(choices=[('L1', 'Lab 1'), ('L2', 'Lab 2'), ('L3', 'Lab 3')], default='L1', max_length=5)),
                ('flag', models.CharField(choices=[(1, '1'), (0, '0')], max_length=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='approve',
            name='data',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reject',
        ),
        migrations.AddField(
            model_name='waterdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='waterdata',
            name='laboratory',
            field=models.CharField(choices=[('L1', 'Lab 1'), ('L2', 'Lab 2'), ('L3', 'Lab 3')], default='L1', max_length=5),
        ),
        migrations.AddField(
            model_name='waterdata',
            name='lat',
            field=models.FloatField(default=78.123445),
        ),
        migrations.AddField(
            model_name='waterdata',
            name='lon',
            field=models.FloatField(default=78.123445),
        ),
        migrations.AddField(
            model_name='waterdata',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waterdata',
            name='water_body_name',
            field=models.CharField(default='Ganga', max_length=140),
        ),
        migrations.DeleteModel(
            name='approve',
        ),
    ]
