# Generated by Django 2.0.2 on 2018-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0008_auto_20180330_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterdata',
            name='status',
            field=models.CharField(default='un-usable', max_length=140),
        ),
        migrations.AddField(
            model_name='waterdatatemp',
            name='status',
            field=models.CharField(default='un-usable', max_length=140),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='laboratory',
            field=models.CharField(choices=[('lab1', 'Lab 1'), ('lab2', 'Lab 2'), ('lab3', 'Lab 3')], default='L1', max_length=5),
        ),
        migrations.AlterField(
            model_name='waterdatatemp',
            name='laboratory',
            field=models.CharField(choices=[('lab1', 'Lab 1'), ('lab2', 'Lab 2'), ('lab3', 'Lab 3')], default='L1', max_length=5),
        ),
    ]
